# Generated by Django 5.0.14 on 2025-07-02 11:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('correo', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
            ],
        ),
        migrations.CreateModel(
            name='CorrespondenciaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.PositiveIntegerField(unique=True, verbose_name='Número')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('fecha_recepcion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de recepción')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='entradas/', verbose_name='Archivo adjunto')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='correspondencia_app.gestor', verbose_name='Gestor')),
            ],
        ),
    ]
