# Generated by Django 5.0.14 on 2025-07-04 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='CorrespondenciaSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=50)),
                ('fecha_recepcion', models.DateField()),
                ('remitente', models.CharField(max_length=100)),
                ('destinatario', models.CharField(max_length=100)),
                ('asunto', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('finalizado', 'Finalizado')], max_length=20)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='adjuntos_salida/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('departamento_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correspondencia_app.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='CorrespondenciaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=50)),
                ('fecha_recepcion', models.DateField()),
                ('remitente', models.CharField(max_length=100)),
                ('destinatario', models.CharField(max_length=100)),
                ('asunto', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('finalizado', 'Finalizado')], max_length=20)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='adjuntos_entrada/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('departamento_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correspondencia_app.departamento')),
            ],
        ),
    ]
