# Generated by Django 5.0.14 on 2025-05-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorrespondenciaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=100)),
                ('fecha_recepcion', models.DateField()),
                ('remitente', models.CharField(max_length=255)),
                ('destinatario', models.CharField(max_length=255)),
                ('asunto', models.TextField()),
                ('departamento_destino', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=50)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='adjuntos/')),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
    ]
