# Generated by Django 5.0.14 on 2025-07-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestor',
            name='departamento',
        ),
        migrations.AlterField(
            model_name='entradacorrespondencia',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='archivos_entrada/'),
        ),
        migrations.AlterField(
            model_name='entradacorrespondencia',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='entradacorrespondencia',
            name='fecha_recepcion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='entradacorrespondencia',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gestor',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salidacorrespondencia',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='archivos_salida/'),
        ),
        migrations.AlterField(
            model_name='salidacorrespondencia',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='salidacorrespondencia',
            name='fecha_envio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salidacorrespondencia',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
