# Generated by Django 5.0.14 on 2025-07-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrespondenciaSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20)),
                ('fecha_envio', models.DateField()),
                ('remitente', models.CharField(max_length=100)),
                ('destinatario', models.CharField(max_length=100)),
                ('asunto', models.TextField()),
                ('departamento_origen', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='salidas/')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
