# Generated by Django 5.0.14 on 2025-07-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correspondenciasalida',
            old_name='departamento_origen',
            new_name='departamento_destino',
        ),
        migrations.RemoveField(
            model_name='correspondenciasalida',
            name='remitente',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='departamento',
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='asunto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='numero_documento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondenciasalida',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='archivos/'),
        ),
        migrations.AlterField(
            model_name='correspondenciasalida',
            name='asunto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='correspondenciasalida',
            name='numero_documento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='correspondenciasalida',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='gestor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
