# Generated by Django 5.0.14 on 2025-06-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentManager',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre del gestor')),
            ],
            options={
                'verbose_name': 'Gestor de Documentos',
                'verbose_name_plural': 'Gestores de Documentos',
                'db_table': 'Document_manager',
            },
        ),
        migrations.AlterModelOptions(
            name='correspondenciaentrada',
            options={'verbose_name': 'Entrada de Correspondencia', 'verbose_name_plural': 'Entradas de Correspondencia'},
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='adjuntos/', verbose_name='Archivo adjunto'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='asunto',
            field=models.TextField(verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='departamento_destino',
            field=models.CharField(max_length=255, verbose_name='Departamento destino'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='destinatario',
            field=models.CharField(max_length=255, verbose_name='Destinatario'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='fecha_recepcion',
            field=models.DateField(verbose_name='Fecha de recepción'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='numero_documento',
            field=models.CharField(max_length=100, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='remitente',
            field=models.CharField(max_length=255, verbose_name='Remitente'),
        ),
        migrations.AlterModelTable(
            name='correspondenciaentrada',
            table='correspondencia_app_correspondenciaentrada',
        ),
    ]
