# Generated by Django 5.0.14 on 2025-07-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=50)),
                ('fecha_recepcion', models.DateField()),
                ('remitente', models.CharField(max_length=100)),
                ('destinatario', models.CharField(max_length=100)),
                ('asunto', models.TextField()),
                ('departamento_destino', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='entradas/')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=50)),
                ('fecha_envio', models.DateField()),
                ('destinatario', models.CharField(max_length=100)),
                ('remitente', models.CharField(max_length=100)),
                ('asunto', models.TextField()),
                ('departamento_origen', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='salidas/')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='correspondenciasalida',
            name='departamento_origen',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='correo',
        ),
        migrations.AddField(
            model_name='gestor',
            name='departamento',
            field=models.CharField(default='Sin departamento', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CorrespondenciaEntrada',
        ),
        migrations.DeleteModel(
            name='CorrespondenciaSalida',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
    ]
