# Generated by Django 5.0.14 on 2025-07-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia_app', '0002_rename_departamento_origen_correspondenciasalida_departamento_destino_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correspondenciasalida',
            old_name='departamento_destino',
            new_name='departamento_origen',
        ),
        migrations.AddField(
            model_name='correspondenciasalida',
            name='remitente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='entradas/'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='asunto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='destinatario',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='numero_documento',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='remitente',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='correspondenciasalida',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='salidas/'),
        ),
        migrations.AlterField(
            model_name='correspondenciasalida',
            name='asunto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='correspondenciasalida',
            name='destinatario',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='correspondenciasalida',
            name='numero_documento',
            field=models.CharField(max_length=50),
        ),
    ]
