# Generated by Django 5.0.14 on 2025-07-11 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia_app', '0002_remove_gestor_departamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gestor',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gestor',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
