# Generated by Django 5.0.14 on 2025-07-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia_app', '0002_entrada_salida_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrespondenciaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20)),
                ('fecha_recepcion', models.DateField()),
                ('remitente', models.CharField(max_length=100)),
                ('destinatario', models.CharField(max_length=100)),
                ('asunto', models.TextField()),
                ('departamento_destino', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='adjuntos_entrada/')),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorrespondenciaSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20)),
                ('fecha_envio', models.DateField()),
                ('remitente', models.CharField(max_length=100)),
                ('destinatario', models.CharField(max_length=100)),
                ('asunto', models.TextField()),
                ('departamento_origen', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='adjuntos_salida/')),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Entrada',
        ),
        migrations.DeleteModel(
            name='Salida',
        ),
        migrations.AddField(
            model_name='gestor',
            name='correo',
            field=models.EmailField(default='correo@ejemplo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='correo@ejemplo.com', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
