# Generated by Django 5.0.14 on 2025-07-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia_app', '0003_gestor_cargo_gestor_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestor',
            name='cargo',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gestor',
            name='departamento',
            field=models.CharField(default='sin datos', max_length=100),
            preserve_default=False,
        ),
    ]
