# Generated by Django 5.0.14 on 2025-07-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia_app', '0003_correspondenciaentrada_correspondenciasalida_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='departamento',
        ),
        migrations.AddField(
            model_name='gestor',
            name='telefono',
            field=models.CharField(default='exit', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='entradas/'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='destinatario',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='numero_documento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='remitente',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='correspondenciasalida',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='salidas/'),
        ),
        migrations.AlterField(
            model_name='correspondenciasalida',
            name='destinatario',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='correspondenciasalida',
            name='numero_documento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='correspondenciasalida',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondenciasalida',
            name='remitente',
            field=models.CharField(max_length=200),
        ),
    ]
