# Generated by Django 5.0.14 on 2025-06-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia_app', '0003_userimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correspondenciaentrada',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documentmanager',
            options={},
        ),
        migrations.RemoveField(
            model_name='correspondenciaentrada',
            name='archivo_adjunto',
        ),
        migrations.RemoveField(
            model_name='documentmanager',
            name='name',
        ),
        migrations.AddField(
            model_name='documentmanager',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='documentmanager',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='documentmanager',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='asunto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='departamento_destino',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='destinatario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('EN_PROCESO', 'En proceso'), ('FINALIZADO', 'Finalizado')], default='RECIBIDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='fecha_recepcion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='numero_documento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='remitente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documentmanager',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='correspondenciaentrada',
            table=None,
        ),
        migrations.AlterModelTable(
            name='documentmanager',
            table=None,
        ),
        migrations.DeleteModel(
            name='UserImage',
        ),
    ]
