# Generated by Django 5.0.14 on 2025-07-09 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia_app', '0004_delete_usuario_remove_gestor_departamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaCorrespondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=50)),
                ('fecha_recepcion', models.DateField()),
                ('remitente', models.CharField(max_length=100)),
                ('destinatario', models.CharField(max_length=100)),
                ('asunto', models.TextField()),
                ('departamento_destino', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('finalizado', 'Finalizado')], max_length=50)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='entradas_adjuntos/')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalidaCorrespondencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=50)),
                ('fecha_envio', models.DateField()),
                ('remitente', models.CharField(max_length=100)),
                ('destinatario', models.CharField(max_length=100)),
                ('asunto', models.TextField()),
                ('medio_envio', models.CharField(choices=[('correo', 'Correo'), ('mensajero', 'Mensajero'), ('otro', 'Otro')], max_length=50)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='salidas_adjuntos/')),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CorrespondenciaEntrada',
        ),
        migrations.DeleteModel(
            name='CorrespondenciaSalida',
        ),
        migrations.AddField(
            model_name='gestor',
            name='cargo',
            field=models.CharField(default='sin asignar', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gestor',
            name='departamento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
