# Generated by Django 5.0.14 on 2025-06-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia_app', '0004_alter_correspondenciaentrada_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correspondenciaentrada',
            options={'verbose_name': 'Entrada', 'verbose_name_plural': 'Entradas'},
        ),
        migrations.AlterModelOptions(
            name='documentmanager',
            options={'verbose_name': 'Gestor de Documentos', 'verbose_name_plural': 'Gestores de Documentos'},
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('ENVIADO', 'Enviado')], max_length=20),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='documentmanager',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='documentmanager',
            name='nombre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='documentmanager',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
