# Generated by Django 5.0.14 on 2025-06-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia_app', '0005_alter_correspondenciaentrada_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correspondenciaentrada',
            options={'ordering': ['-fecha_recepcion'], 'verbose_name': 'Entrada de Correspondencia', 'verbose_name_plural': 'Entradas de Correspondencia'},
        ),
        migrations.AlterModelOptions(
            name='documentmanager',
            options={'ordering': ['nombre'], 'verbose_name': 'Gestor de Documentos', 'verbose_name_plural': 'Gestores de Documentos'},
        ),
        migrations.AddField(
            model_name='correspondenciaentrada',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='entradas/', verbose_name='Archivo adjunto'),
        ),
        migrations.AddField(
            model_name='documentmanager',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='gestores/', verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='asunto',
            field=models.CharField(max_length=200, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='departamento_destino',
            field=models.CharField(max_length=100, verbose_name='Departamento destino'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='destinatario',
            field=models.CharField(max_length=100, verbose_name='Destinatario'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='fecha_recepcion',
            field=models.DateField(verbose_name='Fecha de recepción'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='numero_documento',
            field=models.CharField(max_length=50, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='remitente',
            field=models.CharField(max_length=100, verbose_name='Remitente'),
        ),
        migrations.AlterField(
            model_name='documentmanager',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='documentmanager',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='documentmanager',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
    ]
