# Generated by Django 5.0.14 on 2025-07-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia_app', '0005_entradacorrespondencia_salidacorrespondencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestor',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='gestor',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='salidacorrespondencia',
            name='medio_envio',
        ),
        migrations.AddField(
            model_name='salidacorrespondencia',
            name='departamento_origen',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salidacorrespondencia',
            name='estado',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entradacorrespondencia',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='archivos_entrada/'),
        ),
        migrations.AlterField(
            model_name='entradacorrespondencia',
            name='estado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='entradacorrespondencia',
            name='observaciones',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salidacorrespondencia',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='salidas/'),
        ),
        migrations.AlterField(
            model_name='salidacorrespondencia',
            name='destinatario',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='salidacorrespondencia',
            name='numero_documento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salidacorrespondencia',
            name='remitente',
            field=models.CharField(max_length=255),
        ),
    ]
