# Generated by Django 5.0.14 on 2025-06-29 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia_app', '0006_alter_correspondenciaentrada_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondenciaentrada',
            name='gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='correspondencia_app.documentmanager', verbose_name='Gestor responsable'),
        ),
    ]
