# Generated by Django 5.0.14 on 2025-07-01 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia_app', '0007_correspondenciaentrada_gestor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correspondenciaentrada',
            options={},
        ),
        migrations.AlterModelOptions(
            name='documentmanager',
            options={},
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='archivo_adjunto',
            field=models.FileField(blank=True, null=True, upload_to='entradas/'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='asunto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='departamento_destino',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='destinatario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('En Proceso', 'En Proceso'), ('Cerrado', 'Cerrado')], default='Activo', max_length=50),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='fecha_recepcion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='correspondencia_app.documentmanager'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='numero_documento',
            field=models.CharField(editable=False, help_text='Número secuencial autogenerado', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='remitente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documentmanager',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='gestores/'),
        ),
        migrations.AlterField(
            model_name='documentmanager',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='documentmanager',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='documentmanager',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
