# Generated by Django 5.0.14 on 2025-07-01 21:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondencia_app', '0008_alter_correspondenciaentrada_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='correspondenciaentrada',
            name='departamento_destino',
        ),
        migrations.RemoveField(
            model_name='correspondenciaentrada',
            name='destinatario',
        ),
        migrations.RemoveField(
            model_name='correspondenciaentrada',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='correspondenciaentrada',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='correspondenciaentrada',
            name='remitente',
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='fecha_recepcion',
            field=models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha de recepción'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='numero_documento',
            field=models.IntegerField(editable=False, unique=True, verbose_name='Número de entrada'),
        ),
        migrations.AlterField(
            model_name='correspondenciaentrada',
            name='gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas', to='correspondencia_app.gestor'),
        ),
        migrations.DeleteModel(
            name='DocumentManager',
        ),
    ]
